### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jburel**
* Update omero-gateway version
* Update testNG version
* exclude ``edu.ucar:cdm-core``

### CODE REVIEW

**Review by dominikl — APPROVED** [review]
👍

**Comment by jburel** [comment]
@dgault @sbesson I had to exclude ``edu.ucar:cdm-core`` declared in https://github.com/ome/bioformats/blob/develop/components/formats-gpl/pom.xml#L67
The build fails with the error:
```
[WARNING] The POM for edu.ucar:cdm-core:jar:5.3.3 is missing, no dependency information available
Downloading from ome.maven: https://artifacts.openmicroscopy.org/artifactory/maven/edu/ucar/cdm-core/5.3.3/cdm-core-5.3.3.jar
Downloading from central: https://repo.maven.apache.org/maven2/edu/ucar/cdm-core/5.3.3/cdm-core-5.3.3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.468 s
[INFO] Finished at: 2022-12-15T20:17:55Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project downloader: Could not resolve dependencies for project omero:downloader:jar:0.2.3-SNAPSHOT: Could not find artifact edu.ucar:cdm-core:jar:5.3.3 in ome.maven (https://artifacts.openmicroscopy.org/artifactory/maven) -> [Help 1]
```

**Review by sbesson — CHANGES_REQUESTED** [review]
I think you need to add the UniData releases repository to the POM - see https://docs.openmicroscopy.org/bio-formats/6.11.1/developers/java-library.html

**Comment by jburel** [comment]
> https://github.com/ome/bioformats/blob/develop/components/formats-gpl/pom.xml#L67

**Comment by jburel** [comment]
> I think you need to add the UniData releases repository to the POM - see https://docs.openmicroscopy.org/bio-formats/6.11.1/developers/java-library.html

I had the repo already in the minimal-omero-client that's why I did not notice the error. Thanks

**Comment by jburel** [comment]
@sbesson everything should work now . Thanks for spotting it

**Review by sbesson — APPROVED** [review]

**Pull request merged**
